# Generated by Django 5.2.2 on 2025-06-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alcohol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='barra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listaaalcohol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listadealcohol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={},
        ),
    ]
